export const POSTS = [
	{
		_id: "1",
		text: "Let's build a fullstack WhatsApp clone with NEXT.JS 14 😍",
		img: "/posts/post1.png",
		user: {
			username: "Maha",
			profileImg: "/avatars/girl2.png",
			fullName: "Mahalakshmi Pilla",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "Srija",
					profileImg: "/avatars/girl1.png",
					fullName: "Srija Lattala",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "2",
		text: "How you guys doing? 😊",
		user: {
			username: "Maha",
			profileImg: "/avatars/girl2.png",
			fullName: "Mahalakshmi Pilla",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "Kavya",
					profileImg: "/avatars/girl3.png",
					fullName: "Kavya Pilla",
				},
			},
		],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894"],
	},
	{
		_id: "3",
		text: "Astronaut in a room of drawers, generated by Midjourney. 🚀",
		img: "/posts/post2.png",
		user: {
			username: "Chinna",
			profileImg: "/avatars/boy3.png",
			fullName: "Chinnarao Pilla",
		},
		comments: [],
		likes: ["6658s891", "6658s892", "6658s893", "6658s894", "6658s895", "6658s896"],
	},
	{
		_id: "4",
		text: "I'm learning GO this week. Any tips? 🤔",
		img: "/posts/post3.png",
		user: {
			username: "Roshni",
			profileImg: "/avatars/girl3.png",
			fullName: "Roshni Nekkanti",
		},
		comments: [
			{
				_id: "1",
				text: "Nice Tutorial",
				user: {
					username: "Kavya",
					profileImg: "/avatars/girl3.png",
					fullName: "Kavya Pilla",
				},
			},
		],
		likes: [
			"6658s891",
			"6658s892",
			"6658s893",
			"6658s894",
			"6658s895",
			"6658s896",
			"6658s897",
			"6658s898",
			"6658s899",
		],
	},
];

export const USERS_FOR_RIGHT_PANEL = [
	{
		_id: "1",
		fullName: "Mahalakshmi",
		username: "Maha",
		profileImg: "/avatars/girl3.png",
	},
	{
		_id: "2",
		fullName: "Priya",
		username: "Priya",
		profileImg: "/avatars/girl1.png",
	},
	{
		_id: "3",
		fullName: "Roshni Nekkanti",
		username: "Roshni",
		profileImg: "/avatars/girl3.png",
	},
	{
		_id: "4",
		fullName: "Srija Lattala",
		username: "Srija",
		profileImg: "/avatars/girl2.png",
	},
];